// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEventInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Venue       string `json:"venue"`
	URL         string `json:"url"`
}

type DeleteEventResponse struct {
	DeleteEventID string `json:"deleteEventId"`
}

type Event struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Venue       string `json:"venue"`
	URL         string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateEventInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Venue       *string `json:"venue,omitempty"`
	URL         *string `json:"url,omitempty"`
}
